Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -20,18 +20,28 @@ jobs:
       uses: actions/setup-go@v3
       with:
         go-version: 1.19
+        cache: true
 
     - name: Build Linux
-      run: env GOOS=linux GOARCH=amd64 go build -v ./...
-    
-    - name: Build Windows
-      run: env GOOS=windows GOARCH=amd64 go build -v ./...
-    
-    - name: Build Apple Intel
-      run: env GOOS=darwin GOARCH=amd64 go build -v ./...
-    
-    - name: Build Apple ARM
-      run: env GOOS=darwin GOARCH=arm64 go build -v ./...
-      
-    - name: Test
-      run: go test -v ./...
+      run: | 
+        #!/usr/bin/env bash
+        package_name="shc-exporter"
+
+        platforms=("windows/amd64" "darwin/amd64" "linux/amd64" "darwin/arm64")
+
+        for platform in "${platforms[@]}"
+        do
+          platform_split=(${platform//\// })
+          GOOS=${platform_split[0]}
+          GOARCH=${platform_split[1]}
+          output_name=$package_name'-'$GOOS'-'$GOARCH
+          if [ $GOOS = "windows" ]; then
+            output_name+='.exe'
+          fi	
+          mkdir bin
+          env GOOS=$GOOS GOARCH=$GOARCH go build -o bin/$output_name $package
+          if [ $? -ne 0 ]; then
+              echo 'An error has occurred! Aborting the script execution...'
+            exit 1
+          fi
+        done
